config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:new, :update, :show, :edit, :create, :index, :destroy]

  # get    "articles",          to: "articles#index"

  # get    "articles/new",      to: "articles#new"
  # post   "articles",          to: "articles#create"

  # get    "articles/:id",      to: "articles#show"

  # get    "articles/:id/edit", to: "articles#edit"
  # patch  "articles/:id",      to: "articles#update"

  # delete "articles/:id",      to: "articles#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index # GET /articles
    @articles = Article.all
  end

  def show # GET /articles/:id
  end

  def new # GET /articles/new
    @article = Article.new
  end

  def create # POST /articles
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit # GET /articles/:id/edit
  end

  def update # PATCH /articles/:id
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy # DELETE /articles/:id
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
      @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |a| %>
  <%= a.label :title %><br />
  <%= a.text_field :title %><br />
  <%= a.label :content %><br />
  <%= a.text_area :content %><br />
  <%= a.submit %>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<%= render 'form' %>

<%= link_to "return to the list", "/articles" %>

app/views/articles/index.html.erb
<div class="card">
  <div class='titre'>
    <h1>Articles#index</h1>
  </div>
</div>

<% @articles.each_with_index do |article, index| %>
<div class="card">
  <div class='article'>
      <p><%= index + 1 %> - <%= article.title %> <%= link_to 'show', "/articles/#{article.id}" %> <%= link_to 'edit', edit_article_path(article) %> <%= link_to "delete", article_path(article),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
  </div>
</div>
<% end %>

<%= link_to "add a new article", "/articles/new" %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<%= render 'form' %>

<%= link_to "return to the list", "/articles" %>

app/views/articles/show.html.erb
<div class="card">
  <div class='titre'>
    <h1>Articles#show</h1>
  </div>
</div>

<div class="card">
  <div class='article'>
      <h2><%= @article.id %> - <%= @article.title %></h2>
  </div>
</div>

<div class="card">
  <div class='article'>
      <%= Kramdown::Document.new(@article.content).to_html.html_safe %>
  </div>
</div>

<%= link_to 'edit this article', edit_article_path(@article) %> || <%= link_to "return to the list", "/articles" %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner">
      <div class="container-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>